version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-go-cognito-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rir2bv13zvp9"
s3_prefix = "dev-go-cognito-lambda"
region = "ap-northeast-1"
profile = "nekochans-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
