service: go-cognito-lambda

frameworkVersion: '>=2.0.0 <3.0.0'

plugins:
  - serverless-prune-plugin

provider:
  name: aws
  runtime: go1.x
  stage: ${env:DEPLOY_STAGE}
  region: ap-northeast-1
  profile: ${self:custom.profiles.${self:provider.stage}}
  logRetentionInDays: 3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
  environment:
    DEPLOY_STAGE: ${env:DEPLOY_STAGE}
    TARGET_USER_POOL_ID: ${env:TARGET_USER_POOL_ID}
  httpApi:
    cors: true
    authorizers:
      adminJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.ap-northeast-1.amazonaws.com/${env:TARGET_USER_POOL_ID}
        audience:
          - ${env:NEXT_IDAAS_SERVER_CLIENT_ID}

custom:
  defaultStage: dev
  profiles:
    dev: nekochans-dev
  prune:
    automatic: true
    number: 3

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  customMessage:
    handler: bin/message
    events:
      - cognitoUserPool:
          pool: ${env:TRIGGER_USER_POOL_NAME}
          trigger: CustomMessage
          existing: true
  changePassword:
    handler: bin/change-password
    events:
      - httpApi:
          method: PATCH
          path: /users/passwords
          authorizer:
            name: adminJwtAuthorizer
            scopes:
              - ${env:DEPLOY_STAGE}-cognito-admin-api/admin
