name: cd-master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy To Staging And Development
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Deploy To AWS(dev)
        env:
          DEPLOY_STAGE: dev
          REGION: ${{ secrets.REGION }}
          DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          TARGET_USER_POOL_ID: ${{ secrets.DEV_TARGET_USER_POOL_ID }}
          TRIGGER_USER_POOL_NAME: ${{ secrets.DEV_TRIGGER_USER_POOL_NAME }}
          NEXT_IDAAS_SERVER_CLIENT_ID: ${{ secrets.DEV_NEXT_IDAAS_SERVER_CLIENT_ID }}
          API_DOMAIN_NAME: ${{ secrets.DEV_API_DOMAIN_NAME }}
          CERTIFICATE_ARN: ${{ secrets.DEV_CERTIFICATE_ARN }}
        run: |
          npm run set:dev-aws-credentials
          make deploy
